application: example-engineering
version: 7
runtime: python27
api_version: 1
threadsafe: true

libraries:  
- name: django
  version: "1.5"
- name: PIL
  version: "1.1.7"
- name: MySQLdb
  version: "latest"
- name: ssl
  version: "latest"

env_variables:
  DJANGO_SETTINGS_MODULE: 'example_engineering.settings'

builtins:
- django_wsgi: on

handlers:

- url: /static/main
  static_dir: main/static/main
  expiration: '0'

- url: /static/project
  static_dir: project/static/project
  expiration: '0'

- url: /static/jobs
  static_dir: jobs/static/jobs
  expiration: '0'

- url: /static/example_engineering
  static_dir: example_engineering/static/example_engineering
  expiration: '0'

- url: /static/admin
  static_dir: example_engineering/static/admin
  expiration: '0'

- url: /static/redactor
  static_dir: redactor/static/redactor
  expiration: '0'

- url: /static/admin/css
  static_dir: apmservices_django/static/admin/css
  expiration: '0'

- url: /static/admin/js
  static_dir: apmservices_django/static/admin/js
  expiration: '0'

- url: /favicon\.ico
  static_files: main/static/main/ico/favicon.ico
  upload: main/static/main/ico/favicon\.ico
